# version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    ports:
      - "34113:5678"
    environment:
      - DB_TYPE=sqlite
      - NODE_ENV=production
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-UTC}
      - TZ=${TZ:-UTC}
      # 如果需要启用 webhook,取消下面注释
      # - N8N_HOST=${N8N_HOST:-localhost}
      # - N8N_PROTOCOL=${N8N_PROTOCOL:-http}
      # - N8N_PORT=34113
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:5678/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  n8n_data: